### ISSUE TITLE
Cluster creation V 1.2.0 is no longer available for install

### ISSUE THREAD

**Issue by garjam73** [MicrosoftLearning/WS-013T00-Azure-Stack-HCI#2]
# Module: 03
#### Step: 02

Description of issue
Cluster Creation (Preview) entry (version 1.2.0 is not listed as an available extension in the latest version of WAC

Repro steps:

On the Settings page, select Extensions, on the Extensions panel, select the Installed extensions tab, select the Cluster Creation (Preview) extension entry (version 1.294.0), select Uninstall, and then when prompted to confirm, select OK.
Return to the Extensions panel, select the Available extensions tab, select the Cluster Creation (Preview) entry (version 1.2.0), and then select Install.

**Comment by garjam73** [comment]
without this version you are completely unable to do module 3 labs.
the new cluster creation tool only works for azurestack hci OS

**Comment by TesterTesterson1004** [comment]
Concur - can the course creator here check backchannels and try and determine why it was 'unlisted'?

![image](https://user-images.githubusercontent.com/49700217/98764204-29e3f480-2390-11eb-9f30-11dd23f6c47e.png)


In the meantime, I tried to get a manual process that would allow us to get by this issue - I *think* this will do the trick:

- From within your WSLab-Management VM, access this URL: https://dev.azure.com/WindowsAdminCenter/Windows%20Admin%20Center%20Feed/_packaging

- In the dropdown labelled 'extensions', select and switch to 'WAC'.
![image](https://user-images.githubusercontent.com/49700217/98764286-5566df00-2390-11eb-8194-6072763bb224.png)

![image](https://user-images.githubusercontent.com/49700217/98764295-5a2b9300-2390-11eb-92c5-45dead57f0db.png)
​​
- Scroll down and select 'msft.sme.cluster-creation':

![image](https://user-images.githubusercontent.com/49700217/98764311-5f88dd80-2390-11eb-817b-0062d520a064.png)

- From the 'WAC > msft.sme.cluster-creation 1.2.0' page, select 'Download':

![image](https://user-images.githubusercontent.com/49700217/98764322-64e62800-2390-11eb-82f7-149fac9e4039.png)

- Download the file to a C:\Temp directory on your WSLab-Management VM. 

- Once file is downloaded, in File Explorer, Right-click the C:\Temp dir, select 'Properties' and then the 'Security' tab.

- Select 'Edit' and then 'Add'.

- In the 'Enter the object names to select' enter 'Network Service' and then click OK.

- In the 'Permissions for Temp' dialog box, select the 'Network Service' account and then check the 'Allow' box for Full control:
​
![image](https://user-images.githubusercontent.com/49700217/98764337-6ca5cc80-2390-11eb-9316-42bc5386ccf9.png)

- Click 'OK' and 'OK' again.

- In your Windows Admin Center browser, in 'Settings > Extensions', select the 'Feeds' tab:

![image](https://user-images.githubusercontent.com/49700217/98764344-70d1ea00-2390-11eb-88a2-73f8486507c9.png)

- Click '+ Add'.

- In the 'Add package source' blade, enter C:\Temp into the field, and then click 'Add':

![image](https://user-images.githubusercontent.com/49700217/98764373-847d5080-2390-11eb-9adb-aee7daacbc01.png)

- The notification should return 'Successfully added feed'.

![image](https://user-images.githubusercontent.com/49700217/98764391-8cd58b80-2390-11eb-984f-84dce5f6defe.png)

- Select the 'Available extensions' tab, and you should see the 'Cluster Creation (Preview)' extension, version 1.20 present from the C:\Temp 'feed':

![image](https://user-images.githubusercontent.com/49700217/98764398-93640300-2390-11eb-84cf-32f4b1b983dc.png)

- You should now be able to return to Module 03, Exercise 1, Task 3, Step 3, and proceed with the modules instructions as written.

**Comment by garjam73** [comment]
workaround allows lab to completes sucessfully

**Comment by garjam73** [comment]
closed in error re-opening so workaround is visible

**Comment by TJGitHubUser** [comment]
Exercise 3A was removed from the course, as the cluster creation extension is no longer available. The remaining exercises were renumbered accordingly.
