### ISSUE TITLE
Edge download URI incorrect

### ISSUE THREAD

**Issue by markingram1** [MicrosoftLearning/WS-013T00-Azure-Stack-HCI#25]
# Module: 02
##### Step: 7

The URI in line 62 of the C:\Library\Scenario.ps1 file is not accurate--it returns a 404 error.

It's a pain to try and configure IE to allow a download of the Edge browser from this page:

https://www.microsoft.com/en-us/edge/business/download

Also a hassle attempting to configure IE settings to allow a download of Chrome to then get to a functional Edge download page.

**Comment by FireyJoe** [comment]
I was not able to reproduce this. Edge installed as expected, and I could also access the download from my personal machine. This does not necessarily rule out all issues, of course, but the link at least seems to still point to the Edge installer.

**Comment by markingram1** [comment]
Thank you. Temporary glitch perhaps.
