### ISSUE TITLE
Lab4B - Creating VM from ISO within ClusterStorage>VMStorage

### ISSUE THREAD

**Issue by Miller6025** [MicrosoftLearning/WS-013T00-Azure-Stack-HCI#28]
# Module: 04
#### Step: 00

Description of issue
Unable to select ISO previously uploaded.  No files appear.
Repro steps:

1. Windows Admin Center
2. Click to sccd01.corp.contoso.com
3. Select Virtual Machines
4. Click inventory and then NEW
5. Navigate to the c:\clusterstorage\VMStorage
6. NO ISO appears
![image](https://user-images.githubusercontent.com/38952976/126075237-7e4826da-b265-4490-abee-dfb0ba664dcf.png)
7.  If I go to the VOLUMES and Inventory, click through the VMStorage and OPEN the storage the volume clearly shows the Server2019datacenterevl.iso   
![image](https://user-images.githubusercontent.com/38952976/126075145-a91a37d9-c5dd-46f8-8742-25350531422c.png)
Can anyone assist?

**Comment by Miller6025** [comment]
I have resolved the issue.  When following the upload instructions, I verified the size was the same for the ISO file as on the LAB VM, but did not note that in the Storagevolume it was showing as "partial". Once I copied into the \\h3v\c$ it was fine.

**Comment by TJGitHubUser** [comment]
Thanks for letting us know.!
