### ISSUE TITLE
"Invalid URI" when I Specify the Network Controller REST URI box, and enter https://NCCLUSTER.corp.contoso.com

### ISSUE THREAD

**Issue by garjen55** [MicrosoftLearning/WS-013T00-Azure-Stack-HCI#7]
# Module: 04
#### Step: 03

![InvalidURIError](https://user-images.githubusercontent.com/46939028/108795501-3dd0f200-754c-11eb-993c-e2c8c01d1f75.jpg)
Blocking Issue: I'm getting an "invalid URI" when I Specify the Network Controller REST URI box, and enter https://NCCLUSTER.corp.contoso.com

**Comment by TesterTesterson1004** [comment]
It takes a really long period of time to get past the setup process early in Lab 4A and attempt to repro this issue - but in at least one full run-through I did not encounter the 'invalid URI' error, and was able to proceed further into the subsequent lab instructions successfully.  Uncertain if this means there is some intermittent issue you encountered that I didn't (and that I might encounter if I was able to run multiple fresh lab tests)

 **but can you confirm:**  In your failing test where you were blocked by the 'invalid uri' error, did you implement _both_ edits to the 'SDNExpressModule.psm1' file detailed in this issue?  https://github.com/MicrosoftLearning/WS-013T00-Azure-Stack-HCI/issues/4 

In my successful test I edited @line 2652 to incorporate the OS versions, and also @lines 1282-1301, to remove the leading spaces as seen here:   https://github.com/microsoft/SDN/pull/461/commits/958f16874d30e9bd9c6b018506730f7890d7d252

**Comment by garjen55** [comment]
I did not do this part:
"edited @line 2652 to incorporate the OS versions, and also @lines 1282-1301, to remove the leading spaces as seen here: microsoft/SDN@958f168"so that must be the difference.Thanks for sending me this - I'm glad to have the information.Garrett Jennings
    On Sunday, March 7, 2021, 11:29:58 AM CST, TesterTesterson1004 <notifications@github.com> wrote:  
 
 


It takes a really long period of time to get past the setup process early in Lab 4A and attempt to repro this issue - but in at least one full run-through I did not encounter the 'invalid URI' error, and was able to proceed further into the subsequent lab instructions successfully. Uncertain if this means there is some intermittent issue you encountered that I didn't (and that I might encounter if I was able to run multiple fresh lab tests)

but can you confirm: In your failing test where you were blocked by the 'invalid uri' error, did you implement both edits to the 'SDNExpressModule.psm1' file detailed in this issue? #4

In my successful test I edited @line 2652 to incorporate the OS versions, and also @lines 1282-1301, to remove the leading spaces as seen here: microsoft/SDN@958f168

**Comment by TJGitHubUser** [comment]
This has been fixed.

- Edits & updates to final portion of 4A instructions, both Student & LAK versions
- Added edited/fixed SDNExpressModule.psm1, placed in new /Allfiles dir for easy download.
